// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8OBy3GzmEggxQHW3MGaKmuCvoBL32jN4',
    appId: '1:623517684313:web:9a5d0d854a2ec118319748',
    messagingSenderId: '623517684313',
    projectId: 'crudfirebase-ce541',
    authDomain: 'crudfirebase-ce541.firebaseapp.com',
    storageBucket: 'crudfirebase-ce541.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiEZsuJUBBOz_DcSV7NIfTCkQ83W-CDUY',
    appId: '1:623517684313:android:798b077c50102203319748',
    messagingSenderId: '623517684313',
    projectId: 'crudfirebase-ce541',
    storageBucket: 'crudfirebase-ce541.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0InNWuyE0yyOcw6C15czBy4k4tCCupFE',
    appId: '1:623517684313:ios:baa5ef2ff9e7db22319748',
    messagingSenderId: '623517684313',
    projectId: 'crudfirebase-ce541',
    storageBucket: 'crudfirebase-ce541.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0InNWuyE0yyOcw6C15czBy4k4tCCupFE',
    appId: '1:623517684313:ios:998ba204317e1e87319748',
    messagingSenderId: '623517684313',
    projectId: 'crudfirebase-ce541',
    storageBucket: 'crudfirebase-ce541.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud.RunnerTests',
  );
}
